/*
   Created by Kareem El Sayed
   a class to get the details of the members from the org to the Gym manager
*/
public inherited sharing class MemberController {
  /*
  @AuraEnabled(cacheable=true)
  public static List<Member__c> findMembers(String searchKey) {
    String key = '%' + searchKey + '%';
    return [
      SELECT Id, Name, Fitness_Level__c, Training_Class__c
      FROM Member__c
      WHERE Name LIKE :key
    ];
  }
  */
}
